/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CharactersCharacterIdRouteImport } from './routes/characters/$characterId'
import { Route as EpisodesIndexRouteImport } from './routes/episodes/index'
import { Route as EpisodesEpisodeIdRouteImport } from './routes/episodes/$episodeId'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsLocationIdRouteImport } from './routes/locations/$locationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdRoute = CharactersCharacterIdRouteImport.update({
  id: '/characters/$characterId',
  path: '/characters/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesIndexRoute = EpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesEpisodeIdRoute = EpisodesEpisodeIdRouteImport.update({
  id: '/episodes/$episodeId',
  path: '/episodes/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdRoute = LocationsLocationIdRouteImport.update({
  id: '/locations/$locationId',
  path: '/locations/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/episodes/': typeof EpisodesIndexRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/characters': typeof CharactersIndexRoute
  '/episodes': typeof EpisodesIndexRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/episodes/': typeof EpisodesIndexRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/locations/$locationId'
    | '/characters/'
    | '/episodes/'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/locations/$locationId'
    | '/characters'
    | '/episodes'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/locations/$locationId'
    | '/characters/'
    | '/episodes/'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute
  EpisodesEpisodeIdRoute: typeof EpisodesEpisodeIdRoute
  LocationsLocationIdRoute: typeof LocationsLocationIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  EpisodesIndexRoute: typeof EpisodesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/': {
      id: '/episodes/'
      path: '/episodes'
      fullPath: '/episodes/'
      preLoaderRoute: typeof EpisodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$episodeId': {
      id: '/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof EpisodesEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId': {
      id: '/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof LocationsLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
  EpisodesEpisodeIdRoute: EpisodesEpisodeIdRoute,
  LocationsLocationIdRoute: LocationsLocationIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  EpisodesIndexRoute: EpisodesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
